# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f71527b2948b0e08d20c4ab7f87752ea3cf07a533e9ac58b3ccd2715a1cc6c406f9f0ceae800fefd3321f4448069bf42a57c6aaf8ae3cba0575a2ffaa9e7248a

test:
  secret_key_base: 1da474602b47ef526802712a21e78a798346174c3b39b0da1f545d3a6a40e5ddba3cc56b8855c2272d8c774001c0d59ef5c16e74bb97ed1a7457854a6e92a371

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
